CREATE DATABASE appDown;

USE appDown;

CREATE TABLE UserTable(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	username VARCHAR(40) NOT NULL UNIQUE,
	pwd VARCHAR(100) NOT NULL,
	role VARCHAR(50),
	email VARCHAR(100)
);
